 version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
    depends_on:
      - redis
      - qdrant
      - ollama
    environment:
      - API_CONFIG_PATH=/app/configs/api.yaml
      - REDIS_CONFIG_PATH=/app/configs/redis.yaml
      - OLLAMA_CONFIG_PATH=/app/configs/ollama.yaml
      - QDRANT_CONFIG_PATH=/app/configs/qdrant.yaml
    restart: unless-stopped
    networks:
      - kb-network

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
    depends_on:
      - redis
      - qdrant
      - ollama
    environment:
      - WORKER_CONFIG_PATH=/app/configs/worker.yaml
      - REDIS_CONFIG_PATH=/app/configs/redis.yaml
      - OLLAMA_CONFIG_PATH=/app/configs/ollama.yaml
      - QDRANT_CONFIG_PATH=/app/configs/qdrant.yaml
    restart: unless-stopped
    networks:
      - kb-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-8501}:8501"
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
    depends_on:
      - api
    environment:
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped
    networks:
      - kb-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword}
    restart: unless-stopped
    networks:
      - kb-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped
    networks:
      - kb-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - kb-network

networks:
  kb-network:
    driver: bridge

volumes:
  redis-data:
  qdrant-data:
  ollama-data:
