 server:
  host: '0.0.0.0'
  port: 8000
  workers: 4
  log_level: 'info'
  debug: false
  reload: false

cors:
  allowed_origins:
    - '*'
  allowed_methods:
    - 'GET'
    - 'POST'
    - 'PUT'
    - 'DELETE'
  allowed_headers:
    - '*'

security:
  api_key_header: 'X-API-Key'
  api_key: 'your-api-key-here'  # 开发环境默认密钥，生产环境应更改
  jwt_secret: 'your-jwt-secret-here'  # 开发环境默认密钥，生产环境应更改
  token_expire_minutes: 1440  # 24小时

rate_limiting:
  enabled: true
  max_requests: 100
  time_window_seconds: 60
